theme = "PaperMod"
baseURL = "https://dittorahmat.github.io/"

[params]
  title = "Data with Ditto"
  description = "Exploring the world of data, one insight at a time. Join Ditto on a journey through data engineering, machine learning, and everything in between."
  mainSections = []
  paginate = 5
  mermaid = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 30
