baseURL = 'https://dittorahmat.github.io/'
languageCode = 'en-us'
title = 'Data With Ditto'
theme = "ananke"
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
